# Generated by Django 4.1.1 on 2022-11-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='staffname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='ph_no',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='usertype',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(default='a', max_length=250, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='staff',
            name='district',
            field=models.CharField(default='a', max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phoneno',
            field=models.IntegerField(default='0000000000', verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='staff',
            name='state',
            field=models.CharField(default='kerala', max_length=25, verbose_name='Name'),
        ),
    ]
