# Generated by Django 4.1.1 on 2022-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_rename_username_staff_staffname_remove_staff_ph_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='district',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phoneno',
            field=models.IntegerField(verbose_name='Phone number'),
        ),
    ]
