# Generated by Django 4.1.1 on 2022-11-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0006_rename_staffname_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=25, verbose_name='Password'),
        ),
    ]
