# Generated by Django 4.1.1 on 2022-11-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0009_alter_staff_photo_alter_staff_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='verification',
        ),
    ]
