# Generated by Django 4.1.1 on 2022-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0011_staff_gender_staff_photo_staff_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='address',
            field=models.CharField(default='a', max_length=250, verbose_name='Name'),
        ),
    ]
