# Generated by Django 4.1.1 on 2022-11-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0013_alter_user_details_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.CharField(default='a', max_length=250, verbose_name='Name'),
        ),
    ]
