# Generated by Django 4.1.1 on 2022-11-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0015_alter_user_details_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='address',
        ),
    ]
