# Generated by Django 4.1.1 on 2022-12-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0016_remove_user_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop_id',
            field=models.IntegerField(default=1, verbose_name='shop id'),
        ),
    ]
