# Generated by Django 4.1.1 on 2022-12-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0018_rename_product_name_products_productname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='shop_id',
        ),
    ]
