# Generated by Django 4.1.1 on 2022-12-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0019_remove_products_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop_id',
            field=models.IntegerField(default=1, verbose_name='shop id'),
        ),
    ]
