# Generated by Django 4.1.1 on 2022-12-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0020_products_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=25)),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('number', models.CharField(max_length=25)),
                ('cvv', models.CharField(max_length=25)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('product_id', models.IntegerField(verbose_name='Id of product')),
            ],
        ),
    ]
