# Generated by Django 4.1.1 on 2022-12-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0023_remove_purchase_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_id',
            field=models.IntegerField(default=1, verbose_name='Id of product'),
        ),
    ]
