# Generated by Django 4.1.1 on 2022-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0024_purchase_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_id',
            field=models.IntegerField(verbose_name='Id of product'),
        ),
    ]
