# Generated by Django 4.1.1 on 2022-12-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0025_alter_purchase_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_id',
        ),
    ]
