# Generated by Django 4.1.1 on 2022-12-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0027_remove_purchase_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shop_id',
            field=models.IntegerField(verbose_name='shop id'),
        ),
    ]
