# Generated by Django 4.1.1 on 2022-12-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0028_alter_products_shop_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shops',
        ),
    ]
