# Generated by Django 4.2.6 on 2023-11-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0029_delete_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
