# Generated by Django 4.2.6 on 2023-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0030_alter_user_details_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
